### ISSUE TITLE
Mod suggestion: Vanilla Hammers/Excavators

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/DoIAmCake#14]
The server has transitioned into 1.17.1, and from what I have been told will remain _extremely_ light this season. My one request would be these two mods which add generic hammers and their shovel equivalent for making mining less a chore. If I am wrong about the light season then I apologize and please correct me, but I personally much prefer a slightly faster mining process. 
Thanks for coming to my Ted Talk

[https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers-forge](url)
[https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators-forge](url)

**Comment by Tamaized** [comment]
No mods are to be added in Season 7. Mods will return in Season 8.

**Comment by EvergreenSystems** [comment]
That's fair, is it running similar to the last set with a new season once a beta is released or am I just second-guessing everything?

**Comment by Tamaized** [comment]
That's correct, yes. Every major mc port will have at least 2 seasons like this. 1.12 had this as well but ended up having 4 total seasons due to the length of development on that version.
Skylight Forest development on its own brings about a new season as well whenever thats worked on.

We always do a single season of just TF then mods come back in the following season once we hit curseforge or just about are ready for curseforge.

**Comment by EvergreenSystems** [comment]
Beautiful, thanks for the clarification
